# fly.toml app configuration file generated for infra-monitor on 2024-05-09T18:48:43+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'infra-monitor'
primary_region = "sin"

[build]
  image = "prom/prometheus"

[[mounts]]
  source = 'prometheus_vol'
  destination = '/prometheus'
  auto_extend_size_threshold = 90
  auto_extend_size_increment = "1GB"
  auto_extend_size_limit = "30GB"

[[services]]
  internal_port = 9090
  protocol = "tcp"
  auto_stop_machines = false
  auto_start_machines = false 
  min_machines_running = 1
  [[services.ports]]
    handlers = ["http", "tls"]
    port = 9090

[[files]]
  guest_path = '/etc/prometheus/prometheus.yml'
  local_path = './config/prometheus.yml'

[[files]]
  guest_path = '/etc/prometheus/alerting_rules/node-exporter.rules.yml'
  local_path = './config/alerting_rules/node-exporter.rules.yml'

[[files]]
  guest_path = '/etc/prometheus/alerting_rules/blackbox.rules.yml'
  local_path = './config/alerting_rules/blackbox.rules.yml'

[[vm]]
  size = 'shared-cpu-1x'
  memory = '256mb'
